### ISSUE TITLE
Images (Opera Mini)

### ISSUE THREAD

**Issue by marisabivi** [stevebickram/stevebickram#12]
You can scroll sideways with your billboard quite a bit (I've zoomed out in the photo, so you don't see the white space next to the portfolio when it isn't zoomed out) . Also your name doesn't show. 
![img_9440](https://cloud.githubusercontent.com/assets/6371052/10368833/457137f4-6da5-11e5-96ca-bb948079dfd1.PNG)

**Comment by benmarley** [comment]
same issue on windows 8 mobile device
