### ISSUE TITLE
Multiple issues

### ISSUE THREAD

**Issue by annamisak** [stevebickram/stevebickram#2]
On mobile phone test, these issues were detected:

-It is not responsive, I have to scroll to the side to view full page
-Cover image is taking a long time to load
-The colour contrast for links over billboard image is very low
-There is a lot of amount of white space before welcome message

**Comment by shelbyboyd** [comment]
Android - internet explorer has the same non responsive issue, and contact button in green is hard to see  (contrast). Also small amount of padding at the top before your image.

**Comment by jamie-smith8** [comment]
this is happening... it seems to not want to take up the full screen.
![img_1173](https://cloud.githubusercontent.com/assets/6372772/10367835/9c98ea68-6da0-11e5-83c9-b2a750b9eae1.PNG)
