### ISSUE TITLE
Extra Space Above Nav Bar (Safari 9)

### ISSUE THREAD

**Issue by valeriebordeleau** [stevebickram/stevebickram#6]
![screen shot 2015-10-08 at 9 28 17 am](https://cloud.githubusercontent.com/assets/6373198/10367519/004138e2-6d9f-11e5-97f1-2b2187e72cde.png)

Try double checking the padding margins, I had a similar issue with this browser.

**Comment by valeriebordeleau** [comment]
Something similar is happening on the left side as well

**Comment by kayleemenard** [comment]
Ditto for firefox on Nexus 4 in both portrait and landscape mode. I can scroll side to side.

---

_Landscape_
![2015-10-08 14 46 42-1](https://cloud.githubusercontent.com/assets/6373202/10369961/eda1e16c-6daa-11e5-8b10-762141242cd6.png)
![2015-10-08 14 47 18](https://cloud.githubusercontent.com/assets/6373202/10369964/f2999138-6daa-11e5-9dcc-8b5ca162a7d0.png)

---

_Portrait_
![2015-10-08 14 46 09](https://cloud.githubusercontent.com/assets/6373202/10369952/e0d66444-6daa-11e5-90ec-e31523d87b68.png)
